import './AboutPage.css';

const milestones = [
  { year: 'Q1 2024', title: 'The Genesis', desc: 'A small team of AI researchers and developers set out to solve the difficulty of manual video production, creating the initial text-to-script synthesis core.' },
  { year: 'Q3 2024', title: 'Beta Launch', desc: 'Launched the first public beta of VisionForge AI, attracting over 50,000 creators in under a month and generating 1M+ minutes of video.' },
  { year: 'Q1 2025', title: 'Distributed Rendering', desc: 'Introduced high-speed multi-GPU rendering pipelines, cutting down export times from 30 minutes to under 3 minutes per video.' },
  { year: 'Q3 2025', title: 'Creator Ecosystem v2', desc: 'Incorporated ElevenLabs neural voices, advanced subtitle synchronisation, ACRCloud copyright checking, and direct publishing APIs.' }
];

const team = [
  { name: 'Dr. Alex Vance', role: 'Co-Founder & CEO', avatar: '👨‍💻', bio: 'Former DeepMind AI researcher with 12+ years in natural language understanding and machine learning systems.' },
  { name: 'Sarah Jenkins', role: 'Chief Creative Officer', avatar: '👩‍🎨', bio: 'Visual designer and former creative director for major entertainment channels, leading our aesthetic standards.' },
  { name: 'Dmitri Kozlov', role: 'Head of GPU Infrastructure', avatar: '👨‍🚀', bio: 'Ex-rendering engineer at Pixar, optimizing our cloud rendering stack and video engine compiler pipelines.' }
];

export default function AboutPage() {
  return (
    <div className="about-page container">
      {/* Hero Section */}
      <section className="about-hero">
        <span className="about-badge">⚡ OUR VISION</span>
        <h1>We Are Automating the Future of <span className="text-gradient">Video Creation</span></h1>
        <p className="about-subtext">
          VisionForge AI is built on the belief that creating professional-grade video content should be as easy as writing a simple sentence. We bridge the gap between creative imagination and technical execution.
        </p>
      </section>

      {/* Stats Section */}
      <section className="about-stats-grid">
        <div className="astat-card glass-panel">
          <div className="astat-num text-gradient">2.4M+</div>
          <div className="astat-lbl">Videos Exported</div>
        </div>
        <div className="astat-card glass-panel">
          <div className="astat-num text-gradient">180K+</div>
          <div className="astat-lbl">Active Content Creators</div>
        </div>
        <div className="astat-card glass-panel">
          <div className="astat-num text-gradient">500M+</div>
          <div className="astat-lbl">Aggregate Social Views</div>
        </div>
        <div className="astat-card glass-panel">
          <div className="astat-num text-gradient">98.4%</div>
          <div className="astat-lbl">Rendering Uptime</div>
        </div>
      </section>

      {/* Core Values Section */}
      <section className="about-values glass-panel">
        <h2>Our Core Values</h2>
        <div className="values-grid">
          <div className="value-item">
            <span className="value-icon">💡</span>
            <h3>Unrivaled Aesthetics</h3>
            <p>We refuse to make ugly, placeholder videos. Every scene, font, transition, and voice generated by our AI is curated to meet premium agency standards.</p>
          </div>
          <div className="value-item">
            <span className="value-icon">⚡</span>
            <h3>Speed Without Compromise</h3>
            <p>Creativity happens in real time. We constantly optimize our GPU rendering and compilation systems to give creators instant feedback.</p>
          </div>
          <div className="value-item">
            <span className="value-icon">🛡️</span>
            <h3>Creator-First Safety</h3>
            <p>We respect copyright policies and the safety of our users' accounts. That's why we build deep pre-publishing copyright scans into our workflow.</p>
          </div>
        </div>
      </section>

      {/* Timeline Milestones Section */}
      <section className="about-timeline">
        <h2>The Journey So Far</h2>
        <p className="section-subtext">How we evolved from a small research concept to a global video ecosystem.</p>
        <div className="timeline-wrap">
          {milestones.map((m, i) => (
            <div className="timeline-node" key={i} id={`timeline-node-${i}`}>
              <div className="node-year text-gradient">{m.year}</div>
              <div className="node-connector">
                <div className="node-dot" />
                <div className="node-line" />
              </div>
              <div className="node-content glass-panel">
                <h3>{m.title}</h3>
                <p>{m.desc}</p>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Team Section */}
      <section className="about-team">
        <h2>Meet the Innovators</h2>
        <p className="section-subtext">The engineers, designers, and creatives building the engine of future media.</p>
        <div className="team-grid">
          {team.map((member, i) => (
            <div className="team-card glass-panel" key={i} id={`team-member-${i}`}>
              <div className="team-avatar-circle">{member.avatar}</div>
              <h3>{member.name}</h3>
              <div className="team-role">{member.role}</div>
              <p className="team-bio">{member.bio}</p>
            </div>
          ))}
        </div>
      </section>
    </div>
  );
}
